# Generated by Django 3.2 on 2022-10-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, choices=[('Stationary', 'Stationary'), ('Electronics', 'Electronics'), ('Food Items', 'Food Items')], max_length=100)),
                ('quantity', models.PositiveIntegerField(blank=True)),
                ('unit_price', models.PositiveIntegerField(blank=True)),
                ('total_price', models.PositiveIntegerField(blank=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
