# Generated by Django 3.2 on 2022-10-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_productlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='supply_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
