# Generated by Django 3.2 on 2022-10-04 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_staffs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='staffs',
        ),
    ]
